blank_issues_enabled: true
contact_links:
  - name: Substrate Stack Exchange
    url: https://substrate.stackexchange.com
    about: Please ask and answer questions on Stack Exchange.
  - name: Substrate Devhub Github
    url: https://github.com/substrate-developer-hub/
    about: Please open issues and PRs on problems encountered with this site.