menu:
  - quick-start
  - learn
  - install
  - build
  - test
  - deploy
  - maintain
  - tutorials
  - reference
  - community

quick-start:
  title: Quick start
  url: /quick-start/
  pages:
    - title: Substrate at a glance
      url: /quick-start/substrate-at-a-glance/
    - title: Start a node
      url: /quick-start/start-a-node/
    - title: Explore the code
      url: /quick-start/explore-the-code/
    - title: Modify the runtime
      url: /quick-start/modify-the-runtime/

learn:
  title: Learn
  url: /learn/
  pages:
    - title: Welcome to Substrate
      url: /learn/welcome-to-substrate/
    - title: Blockchain basics
      url: /learn/blockchain-basics/
    - title: Architecture and Rust libraries
      url: /learn/architecture/
    - title: Networks and nodes
      url: /learn/networks-and-nodes/
    - title: What can you build
      url: /learn/what-can-you-build/
    - title: Runtime development
      url: /learn/runtime-development/
    - title: Transactions and block basics
      url: /learn/transaction-types/
    - title: Transaction lifecycle
      url: /learn/transaction-lifecycle/
    # - title: Block import pipeline
    # url: /learn/block-import/
    # - title: Extrinsics
    # url: /learn/extrinsics/
    # - title: Execution
    # url: /learn/execution/
    # - title: Runtimes and clients
    # url: /learn/runtimes-and-clients/
    - title: State transitions and storage
      url: /learn/state-transitions-and-storage/
    - title: Accounts, addresses, and keys
      url: /learn/accounts-addresses-keys/
    - title: Rust for Substrate
      url: /learn/rust-basics/
    - title: Offchain operations
      url: /learn/offchain-operations/
    - title: Light clients in Substrate Connect
      url: /learn/light-clients-in-substrate-connect/
    - title: Cryptography
      url: /learn/cryptography/
    - title: Consensus
      url: /learn/consensus/
    - title: Cross-consensus messaging
      url: /learn/xcm-communication/

install:
  title: Install
  url: /install/
  pages:
    - title: Rust toolchain
      url: /install/rust-toolchain/
    - title: Linux
      url: /install/linux/
    - title: macOS
      url: /install/macos/
    - title: Windows
      url: /install/windows/
    - title: Developer tools
      url: /install/developer-tools/
    - title: Troubleshoot Rust issues
      url: /install/troubleshoot-rust-issues/

#design:
# title: Design
# url: /design/
# pages:
#- title: Substrate empowers builders
#  url: /design/substrate-empowers-builders/
#- title: Decide what to build
#  url: /design/decide-what-to-build/
#- title: Execution
#url: /design/execution/
#- title: Runtimes and clients
#url: /design/runtimes-and-clients/
#- title: Pallet design
#url: /design/pallet-design/
#- title: Smart contract pallets
#url: /design/smart-contract-pallets/
#- title: Storage design decisions
#url: /design/storage-design/
#- title: Economic models
#url: /design/economic-models/
build:
  title: Build
  url: /build/
  pages:
    - title: Smart contracts
      url: /build/smart-contracts-strategy/
    - title: Custom pallets
      url: /build/custom-pallets/
    - title: Runtime storage
      url: /build/runtime-storage/
    - title: Transactions, weights, and fees
      url: /build/tx-weights-fees/
    - title: Pallet coupling
      url: /build/pallet-coupling/
    - title: Events and errors
      url: /build/events-and-errors/
    - title: Randomness
      url: /build/randomness/
    - title: Privileged calls and origins
      url: /build/origins/
    - title: Remote procedure calls
      url: /build/remote-procedure-calls/
    - title: Application development
      url: /build/application-development/
    - title: Chain specification
      url: /build/chain-spec/
    - title: Genesis configuration
      url: /build/genesis-configuration/
    - title: Build process
      url: /build/build-process/
    - title: Build a deterministic runtime
      url: /build/build-a-deterministic-runtime/
    - title: Troubleshoot your code
      url: /build/troubleshoot-your-code/
    #- title: Executor
    #url: /build/executor/

test:
  title: Test
  url: /test/
  pages:
    - title: Unit test
      url: /test/unit-testing/
    - title: Debug
      url: /test/debug/
    - title: Benchmark
      url: /test/benchmark/
    - title: Simulate parachains
      url: /test/simulate-parachains/
    - title: Check runtime
      url: /test/check-runtime/

deploy:
  title: Deploy
  url: /deploy/
  pages:
    - title: Prepare to deploy
      url: /deploy/prepare-to-deploy/
    - title: Deployment options
      url: /deploy/deployment-options/
    - title: Keys and network operations
      url: /deploy/keys-and-network-operations/
#   - title: Deploy on a test network
#     url: /deploy/deploy-a-test-network/
#   - title: Deploy a parathread
#     url: /deploy/deploy-a-parathread/
#   - title: Launch a parachain
#     url: /deploy/launch-a-parachain/
maintain:
  title: Maintain
  url: /maintain/
  pages:
    - title: Monitor
      url: /maintain/monitor/
    - title: Runtime upgrades
      url: /maintain/runtime-upgrades/
#   - title: Operate
#     url: /maintain/operate/
#   - title: Client upgrades
#     url: /maintain/client-upgrades/
#   - title: Network upgrades
#     url: /maintain/network-upgrades/
#   - title: Data migration
#     url: /maintain/data-migration/

tutorials:
  title: Tutorials
  url: /tutorials/
  pages:
    - title: Build a blockchain
      url: /tutorials/build-a-blockchain/
      pages:
        - title: Build a local blockchain
          url: /tutorials/build-a-blockchain/build-local-blockchain/
        - title: Simulate a network
          url: /tutorials/build-a-blockchain/simulate-network/
        - title: Add trusted nodes
          url: /tutorials/build-a-blockchain/add-trusted-nodes/
        - title: Authorize specific nodes
          url: /tutorials/build-a-blockchain/authorize-specific-nodes/
        - title: Monitor node metrics
          url: /tutorials/build-a-blockchain/monitor-node-metrics/
        - title: Upgrade a running network
          url: /tutorials/build-a-blockchain/upgrade-a-running-network/
    - title: Build application logic
      url: /tutorials/build-application-logic/
      pages:
        - title: Add a pallet to the runtime
          url: /tutorials/build-application-logic/add-a-pallet/
        #- title: Configure the contracts pallet
        #url: /tutorials/build-application-logic/contracts-pallet/
        - title: Specify the origin for a call
          url: /tutorials/build-application-logic/specify-the-origin-for-a-call/
        - title: Use macros in a custom pallet
          url: /tutorials/build-application-logic/use-macros-in-a-custom-pallet/
        - title: Add offchain workers
          url: /tutorials/build-application-logic/add-offchain-workers/
        - title: Publish custom pallets
          url: /tutorials/build-application-logic/publish-custom-pallets/
        - title: Collectibles workshop
          url: /tutorials/collectibles-workshop/
          pages:
            - title: Pallet builder basics
              url: /tutorials/collectibles-workshop/runtime-and-pallets/
            - title: Prepare a working environment
              url: /tutorials/collectibles-workshop/01-prepare/
            - title: Get oriented
              url: /tutorials/collectibles-workshop/02-orientation/
            - title: Create a new pallet
              url: /tutorials/collectibles-workshop/03-create-pallet/
            - title: Shared and custom types
              url: /tutorials/collectibles-workshop/04-import-traits/
            - title: Add custom storage items
              url: /tutorials/collectibles-workshop/05-add-storage-items/
            - title: Create basic functions
              url: /tutorials/collectibles-workshop/06-first-functions/
            - title: More functions
              url: /tutorials/collectibles-workshop/07-more-functions/
            - title: Add collectibles to the runtime
              url: /tutorials/collectibles-workshop/08-add-collectibles-to-runtime/
    - title: Develop smart contracts
      url: /tutorials/smart-contracts/
      pages:
        - title: Prepare your first contract
          url: /tutorials/smart-contracts/prepare-your-first-contract/
        - title: Develop a smart contract
          url: /tutorials/smart-contracts/develop-a-smart-contract/
        - title: Use maps for storing values
          url: /tutorials/smart-contracts/use-maps-for-storing-values/
        - title: Build a token contract
          url: /tutorials/smart-contracts/build-a-token-contract/
        - title: Troubleshoot smart contracts
          url: /tutorials/smart-contracts/troubleshoot-smart-contracts/
    - title: Build a parachain
      url: /tutorials/build-a-parachain/
      pages:
        - title: Prepare a local relay chain
          url: /tutorials/build-a-parachain/prepare-a-local-relay-chain/
        - title: Connect a local parachain
          url: /tutorials/build-a-parachain/connect-a-local-parachain/
        - title: Acquire a testnet slot
          url: /tutorials/build-a-parachain/acquire-a-testnet-slot/
        - title: Open message passing channels
          url: /tutorials/build-a-parachain/open-message-passing-channels/
        - title: Transfer assets with XCM
          url: /tutorials/build-a-parachain/transfer-assets-with-xcm/
#   - title: Integrate with tools
#     url: /tutorials/integrate-with-tools/
#     pages:
#       - title: Integrate a light client node
#         url: /tutorials/integrate-with-tools/integrate-a-light-client-node/
#       - title: Explore sidecar endpoints
#         url: /tutorials/integrate-with-tools/explore-sidecar-endpoints/
#       - title: Access EVM accounts
#         url: /tutorials/integrate-with-tools/access-evm-accounts/

reference:
  title: Reference
  url: /reference/
  pages:
    - title: Rust API
      url: /reference/rust-api/
    - title: Glossary
      url: /reference/glossary/
    - title: Command-line tools
      url: /reference/command-line-tools/
      pages:
        - title: archive
          url: /reference/command-line-tools/archive/
        - title: memory-profiler
          url: /reference/command-line-tools/memory-profiler/
        - title: node-template
          url: /reference/command-line-tools/node-template/
        # DEPRICATION NOTICE: https://github.com/paritytech/polkadot-launch/issues/189 TODO
        # - title: polkadot-launch
        #   url: /reference/command-line-tools/polkadot-launch/
        - title: polkadot-apps
          url: /reference/command-line-tools/polkadot-apps/
        - title: sidecar
          url: /reference/command-line-tools/sidecar/
        - title: srtool
          url: /reference/command-line-tools/srtool/
        - title: subkey
          url: /reference/command-line-tools/subkey/
        - title: subxt
          url: /reference/command-line-tools/subxt/
        - title: try-runtime
          url: /reference/command-line-tools/try-runtime/
        - title: tx-wrapper
          url: /reference/command-line-tools/tx-wrapper/
    - title: Runtime APIs
      url: /reference/runtime-apis/
    - title: FRAME pallets
      url: /reference/frame-pallets/
    - title: FRAME macros
      url: /reference/frame-macros/
    - title: Account data structures
      url: /reference/account-data-structures/
    - title: Type encoding (SCALE)
      url: /reference/scale-codec/
    - title: Address formats
      url: /reference/address-formats/
    - title: Transaction formats
      url: /reference/transaction-format/
    - title: XCM reference
      url: /reference/xcm-reference/
    - title: How-to reference guides
      url: /reference/how-to-guides/

community:
  title: Community
  url: /community/
  pages:
    - title: Content style guide
      url: /community/content-style-guide/
    - title: Contributor guidelines
      url: /community/contributor-guidelines/
    - title: Template - How-to guide
      url: /community/template-how-to-guide/
    #- title: Article bounties
    #url: /community/article-bounty
    #- title: Contributor dropbox
    #url: /community/contributor-dropbox/
