menu:
  - quick-start
  - docs
  - tutorials
  - reference
  - community

quick-start:
  title: Quick start
  url: /quick-start/

docs:
  title: Docs
  url: /main-docs/
  pages:
    - title: Fundamentals
      url: /main-docs/fundamentals/
      pages:
        - title: Blockchain basics
          url: /main-docs/fundamentals/blockchain-basics/
        - title: Why Substrate?
          url: /main-docs/fundamentals/why-substrate/
        - title: Architecture
          url: /main-docs/fundamentals/architecture/
        - title: Networks and blockchains
          url: /main-docs/fundamentals/node-and-network-types/
        - title: Runtime development
          url: /main-docs/fundamentals/runtime-intro/
        - title: Consensus
          url: /main-docs/fundamentals/consensus/
        - title: Transactions and block basics
          url: /main-docs/fundamentals/transaction-types/
        - title: Transaction lifecycle
          url: /main-docs/fundamentals/transaction-lifecycle/
        # - title: Block import pipeline
        # url: /main-docs/fundamentals/block-import/
        # - title: Extrinsics
        # url: /main-docs/fundamentals/extrinsics/
        # - title: Execution
        # url: /main-docs/fundamentals/execution/
        # - title: Runtimes and clients
        # url: /main-docs/fundamentals/runtimes-and-clients/
        - title: State transitions and storage
          url: /main-docs/fundamentals/state-transitions-and-storage/
        - title: Accounts, addresses, and keys
          url: /main-docs/fundamentals/accounts-addresses-keys/
        - title: Rust for Substrate
          url: /main-docs/fundamentals/rust-basics/
        - title: Offchain operations
          url: /main-docs/fundamentals/offchain-operations/
    - title: Install
      url: /main-docs/install/
      pages:
        - title: Rust toolchain
          url: /main-docs/install/rust-builds/
        - title: Linux
          url: /main-docs/install/linux/
        - title: macOS
          url: /main-docs/install/macos/
        - title: Windows
          url: /main-docs/install/windows/
        - title: Developer tools
          url: /main-docs/install/other-tools/
        - title: Troubleshoot Rust issues
          url: /main-docs/install/troubleshooting/
    #- title: Design
    #url: /main-docs/design/
    #pages:
    #- title: Applications
    #url: /main-docs/design/applications/
    #- title: Execution
    #url: /main-docs/design/execution/
    #- title: Runtimes and clients
    #url: /main-docs/design/runtimes-and-clients/
    #- title: Pallet design
    #url: /main-docs/design/pallet-design/
    #- title: Smart contract pallets
    #url: /main-docs/design/smart-contract-pallets/
    #- title: Storage design decisions
    #url: /main-docs/design/storage-design/
    #- title: Economic models
    #url: /main-docs/design/economic-models/
    - title: Build
      url: /main-docs/build/
      pages:
        - title: Introduction to libraries
          url: /main-docs/build/libraries/
        - title: Build process
          url: /main-docs/build/build-process/
        - title: Runtime storage
          url: /main-docs/build/runtime-storage/
        - title: Transactions, weights, and fees
          url: /main-docs/build/tx-weights-fees/
        - title: Custom pallets
          url: /main-docs/build/custom-pallets/
        - title: Pallet coupling
          url: /main-docs/build/pallet-coupling/
        - title: Events and errors
          url: /main-docs/build/events-errors/
        - title: Randomness
          url: /main-docs/build/randomness/
        - title: Chain specification
          url: /main-docs/build/chain-spec/
        - title: Privileged calls and origins
          url: /main-docs/build/origins/
        - title: Remote procedure calls
          url: /main-docs/build/custom-rpc/
        - title: Application development
          url: /main-docs/build/application-dev/
        - title: Upgrade the runtime
          url: /main-docs/build/upgrade/
        #- title: Best practices
        #url: /main-docs/build/best-practices/
        #- title: Executor
        #url: /main-docs/build/executor/
    - title: Test
      url: /main-docs/test/
      pages:
        - title: Unit test
          url: /main-docs/test/unit-testing/
        - title: Debug
          url: /main-docs/test/debug/
        - title: Benchmark
          url: /main-docs/test/benchmark/
    #- title: Deploy
    #url: /main-docs/deploy/
    # pages:
    #   - title: Migrations
    #     url: /docs/main-docs/deploy/migrate/
    #   - title: Monitor
    #     url: /docs/main-docs/deploy/metrics/
    #   - title: Operate
    #     url: /docs/main-docs/deploy/operate/
    #   - title: Migrations
    #- title: Maintain
    #url: /main-docs/maintain/
    #pages:
    #- title: Upgrades
    #url: /main-docs/maintain/upgrade/
tutorials:
  title: Tutorials
  url: /tutorials/
  pages:
    - title: Get started
      url: /tutorials/get-started/
      pages:
        - title: Build a local blockchain
          url: /tutorials/get-started/build-local-blockchain/
        - title: Simulate a network
          url: /tutorials/get-started/simulate-network/
        - title: Add trusted nodes
          url: /tutorials/get-started/trusted-network/
        - title: Authorize specific nodes
          url: /tutorials/get-started/permissioned-network/
        - title: Monitor node metrics
          url: /tutorials/get-started/node-metrics/
        - title: Upgrade a running network
          url: /tutorials/get-started/forkless-upgrade/
    - title: Work with pallets
      url: /tutorials/work-with-pallets/
      pages:
        - title: Add a pallet to the runtime
          url: /tutorials/work-with-pallets/add-a-pallet/
        - title: Configure the contracts pallet
          url: /tutorials/work-with-pallets/contracts-pallet/
        - title: Use macros in a custom pallet
          url: /tutorials/work-with-pallets/use-macros-in-a-custom-pallet/
        - title: Specify the origin for a call
          url: /tutorials/work-with-pallets/specify-the-origin-for-a-call/
        - title: Publish custom pallets
          url: /tutorials/work-with-pallets/publish-custom-pallets/
    - title: Develop smart contracts
      url: /tutorials/smart-contracts/
      pages:
        - title: Prepare your first contract
          url: /tutorials/smart-contracts/prepare-your-first-contract/
        - title: Develop a smart contract
          url: /tutorials/smart-contracts/develop-a-smart-contract/
        - title: Use maps for storing values
          url: /tutorials/smart-contracts/use-maps-for-storing-values/
        - title: Build a token contract
          url: /tutorials/smart-contracts/build-a-token-contract/
        - title: Troubleshoot smart contracts
          url: /tutorials/smart-contracts/troubleshoot-smart-contracts/
    - title: Connect with other chains
      url: /tutorials/connect-other-chains/
      pages:
        - title: Start a local relay chain
          url: /tutorials/connect-other-chains/local-relay/
        - title: Connect a local parachain
          url: /tutorials/connect-other-chains/local-parachain/
        - title: Connect to Rococo testnet
          url: /tutorials/connect-other-chains/rococo-slot/
        #- title: Send cross-consensus messages (XCM)
        #  url: /tutorials/connect-other-chains/xcm/
    - title: Integrate with tools
      url: /tutorials/integrate-with-tools/
      pages:
        - title: Integrate a light client node
          url: /tutorials/integrate-with-tools/substrate-connect/
        - title: Access EVM accounts
          url: /tutorials/integrate-with-tools/access-evm-accounts/
reference:
  title: Reference
  url: /reference/
  pages:
    - title: Glossary
      url: /reference/glossary/
    - title: Command-line tools
      url: /reference/command-line-tools/
      pages:
        - title: archive
          url: /reference/command-line-tools/archive/
        - title: memory-profiler
          url: /reference/command-line-tools/memory-profiler/
        - title: node-template
          url: /reference/command-line-tools/node-template/
        # DEPRICATION NOTICE: https://github.com/paritytech/polkadot-launch/issues/189 TODO
        # - title: polkadot-launch
        #   url: /reference/command-line-tools/polkadot-launch/
        - title: polkadot-apps
          url: /reference/command-line-tools/polkadot-apps/
        - title: sidecar
          url: /reference/command-line-tools/sidecar/
        - title: srtool
          url: /reference/command-line-tools/srtool/
        - title: subkey
          url: /reference/command-line-tools/subkey/
        - title: subxt
          url: /reference/command-line-tools/subxt/
        - title: try-runtime
          url: /reference/command-line-tools/try-runtime/
        - title: tx-wrapper
          url: /reference/command-line-tools/tx-wrapper/
    - title: Runtime APIs
      url: /reference/runtime-apis/
    - title: FRAME pallets
      url: /reference/frame-pallets/
    - title: Frame macros
      url: /reference/frame-macros/
    - title: Account data structures
      url: /reference/account-data-structures/
    - title: Type encoding (SCALE)
      url: /reference/scale-codec/
    - title: Transaction formats
      url: /reference/transaction-format/
    - title: Cryptography
      url: /reference/cryptography/
    - title: How-to reference guides
      url: /reference/how-to-guides/
community:
  title: Community
  url: /community/
  pages:
    - title: Style guide
      url: /community/style-guide/
    - title: Contributor guidelines
      url: /community/contributor-guidelines/
    - title: Template - How-to guide
      url: /community/template-how-to-guide/
    #- title: Article bounties
      #url: /community/article-bounty
    #- title: Contributor dropbox
      #url: /community/contributor-dropbox/
