menu:
  - quick-start
  - docs
  - tutorials
  - reference

quick-start:
  title: Quick start
  url: /quick-start/quickstart/

docs:
  title: Docs
  url: /main-docs/
  pages:
    - title: Fundamentals
      url: /main-docs/fundamentals/
      pages:
        - title: Blockchain basics
          url: /main-docs/fundamentals/blockchain-basics/
        - title: Why Substrate?
          url: /main-docs/fundamentals/why-substrate/
        - title: Architecture
          url: /main-docs/fundamentals/architecture/
        - title: Networks and blockchains
          url: /main-docs/fundamentals/node-and-network-types/
        - title: Runtime development
          url: /main-docs/fundamentals/runtime-intro/
        - title: Consensus
          url: /main-docs/fundamentals/consensus/
        - title: Transactions and block input
          url: /main-docs/fundamentals/transaction-types/  
        - title: Transaction lifecycle
          url: /main-docs/fundamentals/transaction-lifecycle/
        - title: State transitions and storage
          url: /main-docs/fundamentals/state-transitions-and-storage/
        - title: Accounts, addresses, and keys
          url: /main-docs/fundamentals/accounts-addresses-keys/
        - title: Rust for Substrate
          url: /main-docs/fundamentals/rust-basics/
        - title: Offchain operations
          url: /main-docs/fundamentals/offchain-operations/
    - title: Install
      url: /main-docs/install/
      pages:
        - title: Rust toolchain
          url: /main-docs/install/rust-builds/
        - title: Linux
          url: /main-docs/install/linux/
        - title: macOS
          url: /main-docs/install/macos/
        - title: Windows
          url: /main-docs/install/windows/
        - title: Developer tools
          url: /main-docs/install/other-tools/
        - title: Troubleshoot Rust issues
          url: /main-docs/install/troubleshooting/
    - title: Design
      url: /main-docs/design/
      pages:
        - title: Pallet design
          url: /main-docs/design/pallet-design/
        - title: Smart contract pallets
          url: /main-docs/design/smart-contract-pallets/
        - title: Storage design decisions
          url: /main-docs/design/storage-design/
        - title: Economic models
          url: /main-docs/design/economic-models/
    - title: Build
      url: /main-docs/build/
      pages:
        - title: Introduction to libraries
          url: /main-docs/build/libraries/
        - title: Build process
          url: /main-docs/build/build-process/
        - title: Storage and data structures
          url: /main-docs/build/storage/
        - title: Transaction weights and fees
          url: /main-docs/build/tx-weights-fees/
        - title: Custom pallets
          url: /main-docs/build/custom-pallets/
        - title: Application development
          url: /main-docs/build/frontend/
        - title: Best practices
          url: /main-docs/build/best-practices/
    - title: Test
      url: /main-docs/test/
      pages:
        - title: Benchmark
          url: /main-docs/test/benchmark/
        - title: Unit testing
          url: /main-docs/test/unit-testing/
        - title: Debug
          url: /main-docs/test/debug/
        - title: Deploy on a testnet
          url: /main-docs/test/deploy-on-testnet/
    - title: Deploy
      url: /main-docs/deploy/
      pages:
        - title: Validators
          url: /main-docs/deploy/validators/
        - title: Networking basics
          url: /main-docs/deploy/networking-basics/
        - title: Finality
          url: /main-docs/deploy/finality/
        - title: Genesis construction
          url: /main-docs/deploy/genesis/
        - title: Protecting your network from attacks
          url: /main-docs/deploy/attacks/
    - title: Maintain
      url: /main-docs/maintain/
      pages:
        - title: Monitoring tools
          url: /main-docs/maintain/monitor/
        - title: Upgrades
          url: /main-docs/maintain/upgrade/

tutorials:
  title: Tutorials
  url: /tutorials/
  pages:
    - title: Get started
      url: /tutorials/get-started/
      pages:
        - title: Build a local blockchain
          url: /tutorials/get-started/build-local-blockchain/
        - title: Simulate a network
          url: /tutorials/get-started/simulate-network/
        - title: Add trusted validators
          url: /tutorials/get-started/trusted-network/
        - title: Authorize specific nodes
          url: /tutorials/get-started/permissioned-network/
        - title: Monitor node metrics
          url: /tutorials/get-started/monitor/
        - title: Upgrade the runtime
          url: /tutorials/get-started/forkless-upgrade/
    - title: Work with pallets
      url: /tutorials/pallets/
      pages:
        - title: Add a pallet to the runtime
          url: /tutorials/work-with-pallets/add-a-pallet/
        - title: Configure the contracts pallet
          url: /tutorials/work-with-pallets/contracts-pallet/
        - title: Use macros in a custom pallet
          url: /tutorials/work-with-pallets/custom-pallet/
        #- title: Publish a custom pallet
          #url: /tutorials/work-with-pallets/publish-pallet/
    - title: Connect with other chains
      url: /tutorials/connect-other-chains/
      pages:
        - title: Start a local relay chain
          url: /tutorials/connect-other-chains/relay-chain/
        - title: Connect to a relay chain
          url: /tutorials/connect-other-chains/parachain/
        - title: Deploy a parachain
          url: /tutorials/connect-other-chains/deploy-parachain/
        - title: Connect to Rococo testnet
          url: /tutorials/connect-other-chains/connect-rococo/
        #- title: Connect to Polkadot
          #url: /tutorials/connect-other-chains/connect-polkadot/
        - title: Connect to Ethereum
          url: /tutorials/connect-other-chains/connect-to-evm/
    - title: Develop smart contracts
      url: /tutorials/smart-contracts/
      pages:
        - title: Prepare your first contract
          url: /tutorials/smart-contracts/first-smart-contract/
        - title: Develop a smart contract
          url: /tutorials/smart-contracts/develop-contract/
        - title: Use maps for storing values
          url: /tutorials/smart-contracts/use-mapping/
        - title: Build a token contract
          url: /tutorials/smart-contracts/erc20-token/
        - title: Troubleshoot smart contracts
          url: /tutorials/smart-contracts/sc-common-issues/
reference:
  title: Reference
  url: /reference/
  pages:
    - title: Glossary
      url: /reference/glossary/
    - title: Command-line tools
      url: /reference/command-line-tools/
      pages:
        - title: archive
          url: /reference/command-line-tools/archive/
        - title: memory-profiler
          url: /reference/command-line-tools/memory-profiler/
        - title: node-template
          url: /reference/command-line-tools/node-template/
        - title: subkey
          url: /reference/command-line-tools/subkey/
        - title: try-runtime
          url: /reference/command-line-tools/try-runtime/
    - title: FRAME pallets
      url: /reference/frame-pallets/
    - title: Frame macros
      url: /reference/frame-macros/
    - title: Account data structures
      url: /reference/account-properties/
    - title: Type encoding (SCALE)
      url: /reference/scale-codec/

    - title: Rust API
      url: 'https://docs.substrate.io/rustdocs/"target="_blank'
    - title: How-to reference guides
      url: /reference/how-to-guides/
      pages:
        - title: Basics
          url: /reference/how-to-guides/basics/
        - title: Pallet design
          url: /reference/how-to-guides/pallet-design/
        - title: Weights
          url: /reference/how-to-guides/weights/
        - title: Testing
          url: /reference/how-to-guides/testing/
        - title: Storage migrations
          url: /reference/how-to-guides/storage-migrations/
        - title: Consensus
          url: /reference/how-to-guides/consensus/
        - title: Parachains
          url: /reference/how-to-guides/parachains/
        - title: Tools
          url: /reference/how-to-guides/tools/
        - title: Off-chain workers
          url: /reference/how-to-guides/ocw/
    - title: Cryptography
      url: /reference/cryptography/

#   - 'Community': 
#       - 'community/index.md'
#      - 'Writing style guidelines': 'community/style-guide.md'
#     - 'Site builder guidelines': 'community/site-building.md'
#- 'How-to topic template': 'https://github.com/substrate-developer-hub/substrate-docs/blob/main/static/assets/contribute-templates/how-to-template.md/"target="_blank'
#- 'Bounties': 'community/bounty.md'
#- 'Dropbox': 'faq-dropbox/index.md'
#- 'Playground': 'https://docs.substrate.io/playground/"target="_blank'