menu:
  - quick-start
  - fundamentals
  - install
  - build
  - test
  - tutorials
  - reference
  - community

quick-start:
  title: Quick start
  url: /quick-start/

fundamentals:
  title: Fundamentals
  url: /fundamentals/
  pages:
    - title: Blockchain basics
      url: /fundamentals/blockchain-basics/
    - title: Why Substrate?
      url: /fundamentals/why-substrate/
    - title: Architecture
      url: /fundamentals/architecture/
    - title: Networks and blockchains
      url: /fundamentals/node-and-network-types/
    - title: Runtime development
      url: /fundamentals/runtime-development/
    - title: Consensus
      url: /fundamentals/consensus/
    - title: Transactions and block basics
      url: /fundamentals/transaction-types/
    - title: Transaction lifecycle
      url: /fundamentals/transaction-lifecycle/
    # - title: Block import pipeline
    # url: /fundamentals/block-import/
    # - title: Extrinsics
    # url: /fundamentals/extrinsics/
    # - title: Execution
    # url: /fundamentals/execution/
    # - title: Runtimes and clients
    # url: /fundamentals/runtimes-and-clients/
    - title: State transitions and storage
      url: /fundamentals/state-transitions-and-storage/
    - title: Accounts, addresses, and keys
      url: /fundamentals/accounts-addresses-keys/
    - title: Rust for Substrate
      url: /fundamentals/rust-basics/
    - title: Offchain operations
      url: /fundamentals/offchain-operations/

install:
  title: Install
  url: /install/
  pages:
    - title: Rust toolchain
      url: /install/rust-toolchain/
    - title: Linux
      url: /install/linux/
    - title: macOS
      url: /install/macos/
    - title: Windows
      url: /install/windows/
    - title: Developer tools
      url: /install/developer-tools/
    - title: Troubleshoot Rust issues
      url: /install/troubleshoot-rust-issues/
  #- title: Design
  #url: /design/
  #pages:
  #- title: Applications
  #url: /design/applications/
  #- title: Execution
  #url: /design/execution/
  #- title: Runtimes and clients
  #url: /design/runtimes-and-clients/
  #- title: Pallet design
  #url: /design/pallet-design/
  #- title: Smart contract pallets
  #url: /design/smart-contract-pallets/
  #- title: Storage design decisions
  #url: /design/storage-design/
  #- title: Economic models
  #url: /design/economic-models/
build:
  title: Build
  url: /build/
  pages:
    - title: Introduction to libraries
      url: /build/libraries/
    - title: Build process
      url: /build/build-process/
    - title: Runtime storage
      url: /build/runtime-storage/
    - title: Transactions, weights, and fees
      url: /build/tx-weights-fees/
    - title: Custom pallets
      url: /build/custom-pallets/
    - title: Pallet coupling
      url: /build/pallet-coupling/
    - title: Events and errors
      url: /build/events-and-errors/
    - title: Randomness
      url: /build/randomness/
    - title: Chain specification
      url: /build/chain-spec/
    - title: Privileged calls and origins
      url: /build/origins/
    - title: Remote procedure calls
      url: /build/custom-rpc/
    - title: Application development
      url: /build/application-dev/
    - title: Upgrade the runtime
      url: /build/upgrade/
    #- title: Best practices
    #url: /build/best-practices/
    #- title: Executor
    #url: /build/executor/

test:
  title: Test
  url: /test/
  pages:
    - title: Unit test
      url: /test/unit-testing/
    - title: Debug
      url: /test/debug/
    - title: Benchmark
      url: /test/benchmark/
#- title: Deploy
#url: /deploy/
# pages:
#   - title: Deploy a solo chain
#     url: /docs/deploy/deploy-a-solo-chain/
#   - title: Deploy on a test network
#     url: /docs/deploy/deploy-on-a-test-network/
#   - title: Deploy a parathread
#     url: /docs/deploy/deploy-a-parathread/
#   - title: Deploy a parachain
#     url: /docs/deploy/deploy-a-parachain/
#- title: Maintain
#url: /maintain/
#pages:
#   - title: Monitor
#     url: /docs/main-docs/deploy/metrics/
#   - title: Operate
#     url: /docs/main-docs/deploy/operate/
#   - title: Upgrades and migration
#     url: /main-docs/maintain/upgrades-and-migration/

tutorials:
  title: Tutorials
  url: /tutorials/
  pages:
    - title: Get started
      url: /tutorials/get-started/
      pages:
        - title: Build a local blockchain
          url: /tutorials/get-started/build-local-blockchain/
        - title: Simulate a network
          url: /tutorials/get-started/simulate-network/
        - title: Add trusted nodes
          url: /tutorials/get-started/trusted-network/
        - title: Authorize specific nodes
          url: /tutorials/get-started/permissioned-network/
        - title: Monitor node metrics
          url: /tutorials/get-started/node-metrics/
        - title: Upgrade a running network
          url: /tutorials/get-started/forkless-upgrade/
    - title: Work with pallets
      url: /tutorials/work-with-pallets/
      pages:
        - title: Add a pallet to the runtime
          url: /tutorials/work-with-pallets/add-a-pallet/
        - title: Configure the contracts pallet
          url: /tutorials/work-with-pallets/contracts-pallet/
        - title: Use macros in a custom pallet
          url: /tutorials/work-with-pallets/use-macros-in-a-custom-pallet/
        - title: Specify the origin for a call
          url: /tutorials/work-with-pallets/specify-the-origin-for-a-call/
        - title: Publish custom pallets
          url: /tutorials/work-with-pallets/publish-custom-pallets/
    - title: Develop smart contracts
      url: /tutorials/smart-contracts/
      pages:
        - title: Prepare your first contract
          url: /tutorials/smart-contracts/prepare-your-first-contract/
        - title: Develop a smart contract
          url: /tutorials/smart-contracts/develop-a-smart-contract/
        - title: Use maps for storing values
          url: /tutorials/smart-contracts/use-maps-for-storing-values/
        - title: Build a token contract
          url: /tutorials/smart-contracts/build-a-token-contract/
        - title: Troubleshoot smart contracts
          url: /tutorials/smart-contracts/troubleshoot-smart-contracts/
    - title: Connect with other chains
      url: /tutorials/connect-other-chains/
      pages:
        - title: Prepare a local relay chain
          url: /tutorials/connect-other-chains/prepare-a-local-relay-chain/
        - title: Connect a local parachain
          url: /tutorials/connect-other-chains/local-parachain/
        - title: Connect to Rococo testnet
          url: /tutorials/connect-other-chains/rococo-slot/
        #- title: Send cross-consensus messages (XCM)
        #  url: /tutorials/connect-other-chains/xcm/
    - title: Integrate with tools
      url: /tutorials/integrate-with-tools/
      pages:
        - title: Integrate a light client node
          url: /tutorials/integrate-with-tools/substrate-connect/
        - title: Access EVM accounts
          url: /tutorials/integrate-with-tools/access-evm-accounts/

reference:
  title: Reference
  url: /reference/
  pages:
    - title: Glossary
      url: /reference/glossary/
    - title: Command-line tools
      url: /reference/command-line-tools/
      pages:
        - title: archive
          url: /reference/command-line-tools/archive/
        - title: memory-profiler
          url: /reference/command-line-tools/memory-profiler/
        - title: node-template
          url: /reference/command-line-tools/node-template/
        # DEPRICATION NOTICE: https://github.com/paritytech/polkadot-launch/issues/189 TODO
        # - title: polkadot-launch
        #   url: /reference/command-line-tools/polkadot-launch/
        - title: polkadot-apps
          url: /reference/command-line-tools/polkadot-apps/
        - title: sidecar
          url: /reference/command-line-tools/sidecar/
        - title: srtool
          url: /reference/command-line-tools/srtool/
        - title: subkey
          url: /reference/command-line-tools/subkey/
        - title: subxt
          url: /reference/command-line-tools/subxt/
        - title: try-runtime
          url: /reference/command-line-tools/try-runtime/
        - title: tx-wrapper
          url: /reference/command-line-tools/tx-wrapper/
    - title: Runtime APIs
      url: /reference/runtime-apis/
    - title: FRAME pallets
      url: /reference/frame-pallets/
    - title: FRAME macros
      url: /reference/frame-macros/
    - title: Account data structures
      url: /reference/account-data-structures/
    - title: Type encoding (SCALE)
      url: /reference/scale-codec/
    - title: Transaction formats
      url: /reference/transaction-format/
    - title: Cryptography
      url: /reference/cryptography/
    - title: How-to reference guides
      url: /reference/how-to-guides/

community:
  title: Community
  url: /community/
  pages:
    - title: Content style guide
      url: /community/content-style-guide/
    - title: Contributor guidelines
      url: /community/contributor-guidelines/
    - title: Template - How-to guide
      url: /community/template-how-to-guide/
    #- title: Article bounties
      #url: /community/article-bounty
    #- title: Contributor dropbox
      #url: /community/contributor-dropbox/
