name: Check Links

on:
  pull_request:
    branches: [ main, develop ]

  push:
    # always want to including test-ci for testing gh-action
    branches: [ main, develop, test-ci ]

jobs:
  build-website-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build & push image
        run: |
          docker build -t jimmychu0807/substrate-docs .
          docker push jimmychu0807/substrate-docs

  check-links:
    needs: build-website-image
    runs-on: ubuntu-latest

    services:
      gatsby-app:
        image: jimmychu0807/substrate-docs
        ports:
          - 9000:9000

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Take a 6s nap to ensure gatsby-app ready
        run: sleep 6

      - name: Run `broken-link-check`
        run: |
          yarn install
          yarn checklinks:v3
